import Banner from "./Banner";
import Hero from "./Hero";
import Hero2 from "./Hero2";
import Hero3 from "./Hero3";
import Hero4 from "./Hero4";
import Hero5 from "./Hero5";
import Hero6 from "./Hero6";
import Logo from "./Logo";
import Navbar from "./Navbar";
export { Hero6, Hero5, Hero4, Logo, Hero2, Hero3, Hero, Banner, Navbar };
